name: DataSci
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - rapids-blazing=0.17 
  - python=3.8 
  - cudatoolkit=11.0
  - numpy=1.19.2
  - pandas=1.1.3
  - scikit-learn=0.23.2
  - sphinx=3.2.1
  - pip:
    - gpustat==0.6.0
    - imblearn==0.0
    - missingpy==0.2.0
    - plotly==4.11.0
    - umap-learn==0.4.6
