name: DataSci
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8 
  - numpy=1.19.2
  - pandas=1.1.3
  - scikit-learn=0.23.2
  - sphinx=3.2.1
  - sphinx-rtd-theme=0.5.1
  - pip:
    - imblearn==0.0
    - missingpy==0.2.0
    - plotly==4.11.0
    - seaborn==0.11.1
    - matplotlib==3.3.3
    - pydataset=0.2.0
    - umap-learn==0.4.6
